### ISSUE TITLE
Ah! You have a compose file (my comment in https://github.com/uktrade/trade-remedies-caseworker/pull/3 is redundant. Could you refactor these to use the compose file to simplify them?

### ISSUE THREAD

**Issue by markhigham** [uktrade/trade-remedies-public#3]
Ah! You have a compose file (my comment in https://github.com/uktrade/trade-remedies-caseworker/pull/3 is redundant. Could you refactor these to use the compose file to simplify them?

_Originally posted by @rossmiller in https://github.com/uktrade/trade-remedies-public/pull/1#discussion_r478565576_

**Comment by davecharles** [comment]
No longer relevant
